describe("Click link", function() {
    it("About company", function () {
        cy.visit('http://www.bastion.com.ua/')
        cy.scrollTo(0, 3500)
        cy.wait(2000)
        cy.contains("Винница").should('have.text', 'Винница').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Полтава").should('have.text', 'Полтава').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Днепр").should('have.text', 'Днепр').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Тернополь").should('have.text', 'Тернополь').click()
        cy.scrollTo(0, 3500)
        cy.wait(2000)
        cy.contains("Запорожье").should('have.text', 'Запорожье').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Харьков").should('have.text', 'Харьков').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Ивано-Франковск").should('have.text', 'Ивано-Франковск').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Киев").should('have.text', 'Киев').click()
        cy.wait(1000)
        cy.contains("Черкассы").should('have.text', 'Черкассы').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Кропивницкий").should('have.text', 'Кропивницкий').click()
        cy.scrollTo(0, 3500)
        cy.wait(2000)
        cy.contains("Львов").should('have.text', 'Львов').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Харьков").should('have.text', 'Харьков').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Николаев").should('have.text', 'Николаев').click()
        cy.scrollTo(0, 3500)
        cy.wait(1000)
        cy.contains("Одесса").should('have.text', 'Одесса').click()






        })
    })
