describe("Click link", function() {
    it("Header menu", function () {
        cy.visit('http://www.bastion.com.ua/')
        cy.wait(2000)
        cy.get('.top-nav-item > [href="/pages/about_company"]').should('have.text', 'О компании').click()
        cy.wait(2000)
        cy.get('.current > .side-menu-sub > :nth-child(1) > a').should('have.text', 'Общая информация').click()
        cy.get('.current > .side-menu-sub > :nth-child(2) > a').should('have.text', 'Доставка').click()
        cy.get('.current > .side-menu-sub > :nth-child(3) > a').should('have.text', 'Региональная сеть').click()
        cy.get('.current > .side-menu-sub > :nth-child(4) > a').should('have.text', 'Гарантии').click()
        cy.get('.current > .side-menu-sub > :nth-child(5) > a').should('have.text', 'Вакансии').click()
        cy.get('.current > .side-menu-sub > :nth-child(6) > a').should('have.text', 'Стать клиентом').click()
        cy.get('tbody > :nth-child(1) > :nth-child(2) > input').type('Alex')
        cy.get('#region').select("Odes'ka Oblast'")
        cy.get(':nth-child(3) > :nth-child(2) > input').type('Autoparts')
        cy.get(':nth-child(4) > :nth-child(2) > input').type('Alex')
        cy.get(':nth-child(5) > :nth-child(2) > input').type('0639567646')
        cy.get(':nth-child(6) > :nth-child(2) > input').type('24auto@gmail.com')
        cy.get('textarea').type('Автоматизация на Cypress')
        cy.get('[valign="top"] > [type="text"]').type(7+7+7)
        cy.contains("Отправить").click()
        cy.wait(2000)
        cy.get('.top-nav-item > [href="/pages/projects"]').should('have.text', 'Проекты').click()
        cy.wait(2000)
        cy.get('.current > .side-menu-sub > :nth-child(1) > a').should('have.text', 'Бош-модуль систем впрыска').click()
        cy.get('.current > .side-menu-sub > :nth-child(2) > a').should('have.text', 'Бош-модуль тормозных систем').click()
        cy.get('.current > .side-menu-sub > :nth-child(3) > a').should('have.text', 'KYB-service').click()
        cy.get('.current > .side-menu-sub > :nth-child(4) > a').should('have.text', 'Кредитная программа для СТО').click()
        cy.get('.current > .side-menu-sub > :nth-child(5) > a').should('have.text', 'Бош-экстра').click()
        cy.get('.current > .side-menu-sub > :nth-child(6) > a').should('have.text', 'Sachs Service').click()
        cy.wait (2000)
        cy.get('.top-nav-item > [href="/pages/action_news"]').should('have.text', 'Акции и новости').click()
        cy.wait(2000)
        cy.get('.current > .side-menu-sub > :nth-child(1) > a').should('have.text', 'Акции').click()
        cy.get('.current > .side-menu-sub > :nth-child(2) > a').should('have.text', 'Новости').click()
        cy.get('.current > .side-menu-sub > :nth-child(3) > a').should('have.text', 'Статьи и обзоры').click()
        cy.get('.current > .side-menu-sub > :nth-child(4) > a').should('have.text', 'События').click()
        cy.get('.current > .side-menu-sub > :nth-child(5) > a').should('have.text', 'Корпоративные издания').click()
        cy.wait (2000)
        cy.get('.top-nav-item > [href="/pages/assortment"]').should('have.text', 'Ассортимент').click()
        cy.wait(2000)
        cy.get('.current > .side-menu-sub > :nth-child(1) > a').should('have.text', 'Общий каталог').click()
        cy.get('.current > .side-menu-sub > :nth-child(2) > a').should('have.text', 'Оборудование для СТО').click()
        cy.get('.current > .side-menu-sub > :nth-child(3) > a').should('have.text', 'Обзор продукции').click()
        cy.wait (2000)
        cy.get('.top-nav-item > [href="/pages/support"]').should('have.text', 'Техническая поддержка').click()
        cy.wait(2000)
        cy.get('.current > .side-menu-sub > :nth-child(1) > a').should('have.text', 'Программа подбора запчастей').click()
        cy.wait (2000)
        cy.get('.top-nav-item > [href="/pages/support"]').click()
        cy.get('.current > .side-menu-sub > :nth-child(2) > a').should('have.text', 'Каталоги поставщиков').click()
        cy.get('.current > .side-menu-sub > :nth-child(3) > a').should('have.text', 'Hot-line для СТО').click()
        cy.get('.current > .side-menu-sub > :nth-child(4) > a').should('have.text', 'Рекомендации производителей').click()
        cy.wait (2000)


        })
    })
